version: 0.2

env:
  variables:
    NODE_ENV: "production"
    PORT: "3000"
phases:
  install:
    runtime-versions:
      nodejs: 22.8.0
    commands:
      - npm install
      - curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
      - yum install -y nodejs
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'