const express = require('express')
const VoiceResponse = require('twilio').twiml.VoiceResponse;
const bodyParser = require('body-parser');
const PORT = 3000

const app = express()

app.use(bodyParser.urlencoded({ extended: false }))

//answers depending on what button is pressed
//the meals are generated by chatGPT

const vegetarianMeals = [
    "Chickpea Curry with Coconut Rice",
    "Stuffed Bell Peppers with Quinoa and Feta",
    "Mushroom Risotto",
    "Vegetable Stir-Fry with Tofu",
    "Spinach and Ricotta Lasagna"
]

const meatMeals = [
    "Grilled Chicken with Lemon and Herbs",
    "Beef Stroganoff",
    "BBQ Pulled Pork Sandwiches",
    "Lamb Curry",
    "Bacon-Wrapped Meatloaf"
]

const fishMeals = [
    "Salmon with Garlic Butter and Dill",
    "Fish Tacos with Lime Crema",
    "Tuna Steaks with Sesame Crust",
    "Shrimp and Spinach Pasta",
    "Baked Cod with Tomato and Olive Sauce"
]

const getRandomMeal = (meals) => meals[Math.floor(Math.random() * meals.length)]

app.post('/voicecall', (req, res) => {
    const twiml = new VoiceResponse()

    const gather = twiml.gather({
        numDigits: 1,
        action: '/handle-key',
        method: 'POST'
    })

    gather.say('Hello! This is a random dinner bot. Press 1 if you want a vegetarian option, press 2 if you want an option with meat and 3 if you want something with fish or seafood.')

    res.type('text/xml')
    res.send(twiml.toString())
})

app.post('/handle-key', (req, res) => {
    const twiml = new VoiceResponse()
    const digit = req.body.Digits
    let randomMeal

    switch (digit) {
        case '1':
            randomMeal = getRandomMeal(vegetarianMeals)
            break
        case '2':
            randomMeal = getRandomMeal(meatMeals)
            break
        case '3':
            randomMeal = getRandomMeal(fishMeals)
            break
        default:
            twiml.say('Sorry that is not a valid option. Try again!')
            twiml.redirect('/voicecall')
            return res.send(twiml.toString())
    }

    twiml.say(`Here is your meal suggestion: ${randomMeal}`)
    twiml.hangup()
    res.type('text/xml')
    res.send(twiml.toString())
})

// test with get
app.get('/voicecall', (req, res) => {
    const twiml = new VoiceResponse()

    const gather = twiml.gather({
        numDigits: 1,
        action: '/handle-key',
        method: 'POST'
    })

    gather.say('Hello! This is random dinner bot. Press 1 if you want a vegetarian option, press 2 if you want an option with meat and 3 if you want something with fish or seafood.')

    res.type('text/xml')
    res.send(twiml.toString())
})

if (require.main === module) {
    app.listen(PORT, () => {
        console.log(`Listening on ${PORT}`)
    })
}

module.exports = { app, getRandomMeal, vegetarianMeals, meatMeals, fishMeals }