name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.8.0'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build app
      run: npm run build

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        aws s3 sync ./ s3://twilio-node-app-2025/ --exclude ".git/*" --exclude "node_modules/*"

    - name: Tag production commits
      if: github.ref == 'refs/heads/main'
      run: |
        TAG="prod-$(date +'%Y-%m-%d')"
        git tag $TAG
        git push origin $TAG